Repository Iryna-Gry/fix-lab-project, pull requests merged in 2023-08, with the labels that each got.

#37 Feature/body/for business page
  app/(layouts)/(components)/CallUsCard.tsx
  app/(pages)/corporate/(components)/BenefitsList.tsx
  app/(pages)/corporate/(components)/ForBusinessSection.tsx
  app/(pages)/corporate/(components)/GadgetsList.tsx
  app/(pages)/corporate/error.tsx
  app/(pages)/corporate/loading.tsx
  app/(pages)/corporate/page.tsx
  public/icons/icon-courier.svg
  public/icons/icon-fast-arrival.svg
  public/icons/icon-notebook.svg
  public/icons/icon-pc.svg
  public/icons/icon-phone.svg
  public/icons/icon-printer.svg
  public/icons/icon-servers.svg
  public/icons/icon-tablet.svg
  public/icons/icon-work-time.svg
  public/images/for-business-table-sm.png
  public/images/for-business-table.png
  tailwind.config.js
Labels: enhancement

#43 Feature diagnostics
  app/(layouts)/(components)/BrandsList.tsx
  app/(layouts)/(components)/ServicesList.tsx
  app/(pages)/repair/(components)/SubcategorySection.tsx
  app/(pages)/repair/[category]/[subcategory]/page.tsx
Labels: feature

#41 refactor: moved and changed adress card component, fix styles
  app/(components)/CardList/CardList.tsx
  app/(layouts)/(components)/AddressLocationCard.tsx
  app/(layouts)/AddressSection.tsx
  tailwind.config.js
Labels: correction
